### ISSUE TITLE
tc-play-2.0/tcplay.c:187: bad loop

### ISSUE THREAD

**Issue by dcb314** [bwalex/tc-play#66]
tc-play-2.0/tcplay.c:187:6: warning: loop exit may only be reached after undefined behavior [-Waggressive-loop-optimizations]

```
   while (valid_cipher_chains[i][k] != NULL) {
        // ...
   }
   // ...
           /* Integrity check */
    if (i >= MAX_CIPHER_CHAINS) {
        tc_log(1, "FATAL: tc_cipher_chains is full!!\n");
        return -1;
    }
```

Suggest check array index _before_ use.

**Comment by bwalex** [comment]
I don't get that even with an explicit `-Waggressive-loop-optimizations` - either way, it sounded like a static analysis failure.
