### ISSUE TITLE
Some memory issues

### ISSUE THREAD

**Issue by topin27** [bwalex/tc-play#67]
### 1. Maybe the return value of dm_info_map() should not be freed by free_info()?

tcplay.c:1593: The return value of check_cipher_chain() is a pointer which is point to the static global variable "tc_cipher_chains[i]", so use free_info() to release the return value of dm_info_map() will cause the tc_cipher_chains' element be freed. Maybe that's a bug?

**Comment by bwalex** [comment]
1 and 2 are addressed now. 3 is intended - it's only ever initialised once, and is expected to be there for the lifetime of the process.
