### ISSUE TITLE
tcplay -c    hangs after some GB

### ISSUE THREAD

**Issue by annadevries1992** [bwalex/tc-play#80]
Hi.
On Dragonfly with Hammer2 FS.
When creating a default tcplay  5GB slice on a file via /dev/vn0   all works fine.
When trying to create a 1TB slice, the tcplay create hangs in dead air after writing/filling a few GB. And the kernel doesn't seem to want to give any process write access to regular filesystems, so i can't run commands anymore.

Please let me know what you want to know, which command outputs you need, etc :)

**Comment by annadevries1992** [comment]
PS.  when doing the tcplay -c -z  is does create te slice,  but then the kernel goes into FS hang/lock modus after writing about 23GB of data to it.

**Comment by bwalex** [comment]
I don't see how that has anything to do with tcplay? tcplay only sets up the mapping, and then is out of the picture.

**Comment by annadevries1992** [comment]
On Mon, 21 Feb 2022 23:51:21 -0800
Alex Hornung ***@***.***> wrote:

> I don't see how that has anything to do with tcplay? tcplay only sets up the mapping, and then is out of the picture.
> 


Dear Alex,
You are not a kind/helpful type of person, are you?  Bit typical for programmers :(
Blame shifting is more the game, ...instead of being social by simply just pointing in the right direction with your
knowledge about how it all works.....
